name: MeridianDB CI pipline

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # TODO: setup publish sdk to npm if changes planned
      - name: deploy mkdocs
        id: cache-mkdocs

        run: |
          # setup identity 
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Ensure the repository is up to date
          git pull 
          mkdocs gh-deploy
